<?php $entries = $this->getEntries(); ?>
<?php foreach ($entries as $entry) : ?>
<div style="padding-left: <?php echo $entry['level'] * 20; ?>px;">
	<?php if ($entry['level'] == 1) : ?>
	<span class="limegreen">
		<?php echo $entry['alias']; ?> (<?php echo $entry['name']; ?>)
	</span>
	<?php else : ?>
	<span class="white">
		<?php echo $entry['alias']; ?> (<?php echo $entry['name']; ?>)
	</span>
	<?php endif; ?>
	(<?php echo implode(' | ', $entry['extras']); ?>)
	<?php if (isset($entry['time'])) : ?>
	| <span class="time <?php echo $this->colorInterval($entry['time']); ?>"><?php echo number_format($entry['time'], 2); ?>ms</span>
	<?php endif; ?>
</div>
<?php endforeach; ?>
