<?php $helper = Mage::helper('developertoolbar'); ?>
<?php foreach ($this->getProfiles() as $profile) : ?>
<div style="padding-left: <?php echo $profile['level'] * 20; ?>px;">
	<?php if ($profile['level'] == 1) : ?>
	<span class="limegreen"><?php echo $profile['name']; ?></span>
	<?php else : ?>
	<span class="white"><?php echo $profile['name']; ?></span>
	<?php endif; ?>
	(<?php echo $profile['class']; ?>)
    - <span class="query-count <?php echo $this->colorQueries($profile['query_count']); ?>"><?php echo $profile['query_count']; ?> queries</span>
    - <span class="time <?php echo $this->colorInterval($profile['duration']); ?>"><?php echo number_format($profile['duration'], 2); ?>ms</span>
</div>
<?php endforeach; ?>
