<?php $panels = $this->getPanels(); ?>
<div class="balloz-toolbar">
	The toolbar.
	<div class="balloz-toolbar-panels-container">
		<?php foreach ($panels as $index => $panel) : ?>
		<div class="balloz-toolbar-panel-container">
			<a href="#" data-panel="<?php echo $index; ?>"><?php echo $this->htmlEscape($panel->getName()); ?></a>
			<div class="balloz-toolbar-panel" id="balloz-toolbar-panel-<?php echo $index; ?>">
				<?php echo $panel->toHtml(); ?>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
</div>